version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    pre_build:
      commands:
        # install depedencies
        - npm install
    build:
      commands:
        - echo Building...
        - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
