import React from "react";

export default function TrademarkRenewalDetails() {
  return (
    <section className="trademark-renewal__allcontents">
      <section className="trademark-renewal__about">
        <div className="trademark-renewal__about-header">
          <h1>TRADEMARK RENEWAL</h1>
        </div>
        <div className="trademark-renewal__about-content">
          <p>
            Once we applied for trademark its validity remains just for 10 years
            after that one needs to file for Trademark Renewal. There are many
            advantages to renewing a trademark. Registration of the trademark
            awards the holder of the trademark many rights that are protected by
            law.
          </p>
          <p>
            Trademark renewal must be filed in advance before the expiry of the
            trademark registration to have the seamless protection of the
            trademark without any chances of litigation and it prevents the
            infringement of the trademark and also provide for restitution in
            case of such infringements.
          </p>
          <p>
            Registration of Trademarks give the owner of the mark right to
            transfer the trademark to another person or company at their will.
            Licensing of trademarks are only possible if the holder of the
            trademark is has registered the trademark, therefore a registered
            trademark holds immense monetary value.
          </p>
          <span className="trademark-registration__process-allcontent">
            <header>1. Protection from Frivolous Litigation:</header>
            <main>
              It is likely to have seamless trademark protection without any
              risks of litigation. Renewal of trademarks makes difficult for
              someone to maintain rights over it other than the trademark owner.
            </main>
            <header>2. Increase of Ownership Rights:</header>
            <main>
              One can get security from infringement of rights over the brand
              name. The exclusive rights over the trademark are continued for 10
              years after each renewal. So it provides permanent protection of
              your brand and goodwill generated by the brand.
            </main>
            <header>3. Brand Name Security:</header>
            <main>
              Renewal of trademark guarantees constant and unhindered protection
              of the brand name. Failure of renewal points to a lapse of legal
              protection in Brand name.
            </main>
            <header>4. Monetary Returns:</header>
            <main>
              A trademark owner has the particular rights to allot or license
              the trademark to someone else in return for some monetary benefit.
              Thus, one can earn a profit from a registered trademark as well.
            </main>
          </span>
        </div>
      </section>
      <section className="trademark-renewal__process">
        <div className="trademark-renewal__process-header">
          <h1>RENEWAL PROCESS AND FORMS</h1>
        </div>
        <div className="trademark-renewal__process-content">
          <span>
            When you are going to renew a trademark you have two options:
            <ol>
              <li>Renew the trademark as it is, or,</li>
              <li>Renew the trademark with changes and alterations</li>
            </ol>
          </span>
          <ul>
            <li>
              <div>
                The application for the renewal of a trademark is the form TM-R.
              </div>
            </li>
            <li>
              <div>
                The application does not need to be filed by the registered
                owner of the trademark, it can be done by an authorised
                representative or an agent.
              </div>
            </li>
            <li>
              <div>
                After filing the application one has to follow the status of the
                application in case any opposition is filed to the registration
                of the trademark. Such opposition can be filed by any person of
                the public.
              </div>
            </li>
            <li>
              <div>
                When the application is approved the trademark will be published
                in the official gazette the Trademark Journal.
              </div>
            </li>
            <li>
              <div>
                If the trademark has been published then the owner of the
                trademark has protection fro another ten years.
              </div>
            </li>
            <li>
              <div>The trademark can be indefinitely renewed.</div>
            </li>
          </ul>
          <p>
            The price for the renewal of a trademark depends upon whether
            application of TM has been submitted physically or it has been filed
            online.
          </p>
          <span>
            <p>For the renewal of a trademark, the following are required:</p>
            <ul>
              <li>
                <div>A copy of the Registration Certificate</div>
              </li>
              <li>
                <div>
                  Copy of form TM-A (form used for the original application for
                  registering the trademark)
                </div>
              </li>
              <li>
                <div>ID and address proof of the applicant</div>
              </li>
              <li>
                <div>
                  Power of attorney if the applicant is an authorised
                  representative or an agent
                </div>
              </li>
            </ul>
          </span>
          <span className="trademark-registration__process-allcontent">
            <header>1. How to Renew a Trademark?</header>
            <main>
              On the notice of the registrar in the prescribed manner to the
              registered owner of the trademarks about the expiry of the
              trademark and payment of the fees for the renewal of the trademark
              with in a period of 6(six) months prior to its expiry.
            </main>
            <header>2. What If the trademark expires?</header>
            <main>
              Well, if you don’t apply for the renewal of the trademark within
              6(six) months after the expiry, there’s still hope, as you can
              apply for a restoration.
            </main>
          </span>
        </div>
      </section>
      <section className="trademark-renewal__restoration">
        <div className="trademark-renewal__restoration-header">
          <h1>RESTORATION OF TRADEMARK</h1>
        </div>
        <div className="trademark-renewal__restoration-content">
          <p>
            There can be times that a person forgets to renew their trademark in
            the given time period. No worries there is still an option available
            in such cases. In the case of failure to renew one can then try to
            restore a trademark. Under Section 25(4) of the Trademark Act, 1999,
            trademark owner can apply for restoration by submitting an
            application and paying the prescribed fee. However, this can only be
            done within 1(one) year of the expiration of the trademark.
          </p>
          <span>
            <p>
              Restoration of a trademark includes an additional fee over the
              renewal fee of:
            </p>
            <ul>
              <li>If filed physically the fees is INR 10,000, or,</li>
              <li>If filed online the fees is INR 9000.</li>
            </ul>
          </span>
        </div>
      </section>
      <section className="trademark-renewal__difference">
        <div className="trademark-renewal__difference-header">
          <h1>
            DIFFERENCE BETWEEN A TRADEMARK REGISTRATION AND A TRADEMARK RENEWAL?
          </h1>
        </div>
        <div className="trademark-renewal__difference-content">
          <p>
            The Trademark Registration is quite different in documentation,
            procedure, the time required and fees from the renewal process
            WHEREAS the Trademark Renewal is done within 6(six) months of
            completing the ten year time period. It is simple and easy to
            handle.
          </p>
        </div>
      </section>
    </section>
  );
}
