/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:63a9d74f-ead1-4c8e-a897-9b63b00a877d",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_B3Do3bL4u",
    "aws_user_pools_web_client_id": "4msm57bukl3qf8slm6orjd13i1",
    "oauth": {
        "domain": "helpingstartups-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "helpingstartups",
            "endpoint": "https://ckzd3icl2c.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
